parameters:
#    api_demo.example.class: Api\DemoBundle\Example

services:
#    api_demo.example:
#        class: %api_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
